Sasha/delete model run
scaleapi/nucleus-python-client pull request #18
Opened 2020-11-05 17:47 UTC by sasha-scale

Added new delete model run functionality into library.  Is pretty simple, tested by deleting some of my extraneous runs on personal datasets.

2020-11-06 00:48 UTC, Nastia39 requested changes

2020-11-06 00:48 UTC, Nastia39 commented on nucleus/__init__.py
> +        print(NUCLEUS_ENDPOINT)
delete these lines

2020-11-06 03:41 UTC, sasha-scale commented on nucleus/__init__.py
> +        print(NUCLEUS_ENDPOINT)
oof sorry about that, resolved.

2020-11-25 23:46 UTC, Nastia39 approved these changes

2020-11-30 21:12 UTC, merged