Annotation Idempotency
scaleapi/nucleus-python-client pull request #30
Opened 2021-02-11 13:57 UTC by jihan-yin

2021-02-11 13:58 UTC, jihan-yin commented on nucleus/__init__.py
> +            self.tqdm_bar = tqdm_notebook.tqdm
Was running into issues calling the api from within a notebook, this resolved it for me

2021-02-16 02:45 UTC, sasha-scale commented on nucleus/__init__.py
> +        annotations: List[Union[BoxAnnotation, PolygonAnnotation]],
omg - nice fix

2021-02-16 02:45 UTC, sasha-scale commented on nucleus/__init__.py
> +        update: bool,
see comment on sister PR - I think this should be optional with default value False

2021-02-16 02:46 UTC, sasha-scale commented on nucleus/__init__.py
> +            print(batch_payload)
remove print statement before merging

2021-02-16 02:47 UTC, sasha-scale commented on nucleus/constants.py
> +#NUCLEUS_ENDPOINT = "https://api.scale.com/v1/nucleus"
remove before merging

2021-02-16 02:48 UTC, sasha-scale commented on nucleus/dataset.py
> +
:nit: extraneous white space

2021-02-16 02:57 UTC, sasha-scale requested changes
I was unable to upload GT annotations without specifying the annotation_id, the error message was "annotation_id must be a string."  I think the issue was that when I did not specify it, it got sent as `None` in the request payload which didn't make it through schema validation

2021-02-17 03:21 UTC, sasha-scale approved these changes
LGTM, tested locally.  Response format does not have annotations_ignored which to me blocks merge, but that is more a comment on the scaleapi Pr than this one.

The unit tests are incredibly thorough!  great jobs!

2021-02-18 06:55 UTC, rkaplan commented on tests/helpers.py
> +    assert_box_annotation_matches_dict(prediction_instance, prediction_dict)
Infinite recursion?

2021-02-18 06:55 UTC, rkaplan commented on tests/helpers.py
> +    assert_polygon_annotation_matches_dict(prediction_instance, prediction_dict)
Infinite recursion?

2021-02-18 07:59 UTC, jihan-yin commented on tests/helpers.py
> +    assert_box_annotation_matches_dict(prediction_instance, prediction_dict)
It's a different function 😄

2021-02-18 07:59 UTC, jihan-yin commented on tests/helpers.py
> +    assert_polygon_annotation_matches_dict(prediction_instance, prediction_dict)
same as above

2021-02-18 08:01 UTC, rkaplan approved these changes

2021-02-19 09:00 UTC, merged