Update results returned by `slice.items()`
scaleapi/nucleus-python-client pull request #368
Opened 2022-10-20 13:51 UTC by jean-lucas

Update the `GET /slice/:slice_id` endpoint to return `items` instead of `dataset_items`

The return type of `items` is based on the type of the slice: `scene, dataset_item, object`

2022-10-21 12:45 UTC, gatli requested changes
We have to keep the `items` property for backwards compatibility. Can you also make sure that `client.slices` populates the type field?

2022-10-21 12:48 UTC, gatli commented
Feel free to skip the `_type` population refactor for now if you don't have time. Its just the `@property` that we have to adhere to that is blocking right now. I don't think anything is calling `_type` right now so listings should still be fast.

Also you can just merge after you've made the change. You have the rights! I just checked 🙂

2022-10-21 12:50 UTC, jean-lucas commented on nucleus/slice.py
> +        )  # CHANGE ME BACK TO `ITEMS_KEY` BEFORE MERGE
Need to merge the `scaleapi` backend first, and then I can change this back. 
Its just so the CI tests passes for now

2022-10-24 08:40 UTC, gatli commented on nucleus/slice.py
> +            self._type = self.info()["type"]
The `client.slices` property hits `slice/` that returns all the relevant info that is then populated in the `Slice.from_request` classmethod. This avoids the `info/` roundtrip for large lists. If we create something that doesn't prepopulate the fields the call to `client.slices` can go from around 1-2s to 100s easily.

```
    @property
    def slices(self) -> List[Slice]:
        response = self.make_request({}, "slice/", requests.get)
        slices = [Slice.from_request(info, self) for info in response]
        return slices
```

2022-10-31 17:58 UTC, gatli approved these changes
LGTM 👍

2022-10-31 17:58 UTC, merged